server:
  port: 8760

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: sms
          uri: http://sms:8091
          predicates:
            - Path=/sms/**
#          filters:
#            - StripPrefix=1 # required to strip the prefix made to the request . Ex /jio/customers request will go to jio service as /customers
#        - id: push
#          uri: lb://push
#          predicates:
#            - Path=/push/**

#info:
#  app:
#    name: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true


#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka