version: '3.8'
services:
  eureka-server:
    container_name: spring-cloud-api-eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:8761" ]
      interval: 20s
      timeout: 5s
      retries: 3
  gateway:
    container_name: spring-cloud-api-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8760:8760"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    links:
      - eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy
  sms-app:
    container_name: spring-cloud-api-sms
    build:
      context: ./sms-app
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    links:
      - eureka-server
    ports:
      - "8091:8091"
    depends_on:
      eureka-server:
        condition: service_healthy
  push-app:
    container_name: spring-cloud-api-push
    build:
      context: ./push-app
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    links:
      - eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy
  email-app:
    container_name: spring-cloud-api-email
    build:
      context: ./email-app
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    links:
      - eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy