spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: sms-app
          uri: http://sms-app:8091
          predicates:
            - Path=/sms/**
        - id: push-app
          uri: http://push-app:8092
          predicates:
            - Path=/push/**
        - id: email-app
          uri: http://email-app:8093
          predicates:
            - Path=/email/**
server:
  port: 8760
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true