spring:
  application:
    name: sms-app
server:
  port: 8091
  servlet:
    contextPath: /sms
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true