spring:
  application:
    name: sms-app
server:
  port: 8091
  servlet:
    contextPath: /sms
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true