spring:
  application:
    name: email-app
server:
  port: 8093
  servlet:
    contextPath: /email
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true