spring:
  application:
    name: push-app
server:
  port: 8092
  servlet:
    contextPath: /push
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true